### ISSUE TITLE
フォント/配色 を決める

### ISSUE THREAD

**Issue by wappon28dev** [lapsquash/lapsquash_pj#4]
UIデザインと重複しているところもありますが, プレゼンや viewer で使う配色やフォントの選定をお願いしたいです.  

条件:
- 日常で使う日本語文字の収録がされていること
- プレゼンでも見やすいフォントであること
- ttf が配布されていること
くらいです.　決まり次第, ここかTeamsに送ってください.　形式がとりあえず画像が良いです.

**Comment by knee0expert** [comment]
フォント: LINE Seed JP_TTF
配色: Material 3 の seed color が 青のやつ(figma参照)
